import 'package:json_annotation/json_annotation.dart';

// This will be generated by build_runner
part 'models.g.dart';

// --- Generic Paginated Response ---

@JsonSerializable(genericArgumentFactories: true)
class PaginatedResponse<T> {
  final List<T> data;
  final Pagination pagination;

  PaginatedResponse({required this.data, required this.pagination});

  // Generic fromJson
  factory PaginatedResponse.fromJson(
    Map<String, dynamic> json,
    T Function(Object? json) fromJsonT,
  ) {
    return _$PaginatedResponseFromJson<T>(json, fromJsonT);
  }

  // Generic toJson
  Map<String, dynamic> toJson(Object Function(T value) toJsonT) {
    return _$PaginatedResponseToJson<T>(this, toJsonT);
  }
}

@JsonSerializable(genericArgumentFactories: true)
class DataResponse<T> {
  final T data;

  DataResponse({required this.data});

  // Generic fromJson
  factory DataResponse.fromJson(
    Map<String, dynamic> json,
    T Function(Object? json) fromJsonT,
  ) {
    return _$DataResponseFromJson<T>(json, fromJsonT);
  }

  // Generic toJson
  Map<String, dynamic> toJson(Object Function(T value) toJsonT) {
    return _$DataResponseToJson<T>(this, toJsonT);
  }
}

// --- Pagination ---

@JsonSerializable()
class Pagination {
  @JsonKey(name: 'last_visible_page')
  final int lastVisiblePage;
  @JsonKey(name: 'has_next_page')
  final bool hasNextPage;
  @JsonKey(name: 'current_page')
  final int currentPage;
  final PaginationItems items;

  Pagination({
    required this.lastVisiblePage,
    required this.hasNextPage,
    required this.currentPage,
    required this.items,
  });

  factory Pagination.fromJson(Map<String, dynamic> json) =>
      _$PaginationFromJson(json);

  Map<String, dynamic> toJson() => _$PaginationToJson(this);
}

@JsonSerializable()
class PaginationItems {
  final int count;
  final int total;
  @JsonKey(name: 'per_page')
  final int perPage;

  PaginationItems({
    required this.count,
    required this.total,
    required this.perPage,
  });

  factory PaginationItems.fromJson(Map<String, dynamic> json) =>
      _$PaginationItemsFromJson(json);

  Map<String, dynamic> toJson() => _$PaginationItemsToJson(this);
}

// --- Main Anime Data Class ---

@JsonSerializable(fieldRename: FieldRename.snake)
class Anime {
  final int malId;
  final String? url;
  final Images? images;
  final Trailer? trailer;
  final bool? approved;
  final List<TitleEntry>? titles;
  final String? title;
  final String? titleEnglish;
  final String? titleJapanese;
  final List<String>? titleSynonyms;
  final String? type;
  final String? source;
  final int? episodes;
  final String? status;
  final bool? airing;
  final Aired? aired;
  final String? duration;
  final String? rating;
  final double? score;
  final int? scoredBy;
  final int? rank;
  final int? popularity;
  final int? members;
  final int? favorites;
  final String? synopsis;
  final String? background;
  final String? season;
  final int? year;
  final Broadcast? broadcast;

  // Reusable MalEntry
  final List<MalEntry>? producers;
  final List<MalEntry>? licensors;
  final List<MalEntry>? studios;
  final List<MalEntry>? genres;
  final List<MalEntry>? explicitGenres;
  final List<MalEntry>? themes;
  final List<MalEntry>? demographics;

  Anime({
    required this.malId,
    this.url,
    this.images,
    this.trailer,
    this.approved,
    this.titles,
    this.title,
    this.titleEnglish,
    this.titleJapanese,
    this.titleSynonyms,
    this.type,
    this.source,
    this.episodes,
    this.status,
    this.airing,
    this.aired,
    this.duration,
    this.rating,
    this.score,
    this.scoredBy,
    this.rank,
    this.popularity,
    this.members,
    this.favorites,
    this.synopsis,
    this.background,
    this.season,
    this.year,
    this.broadcast,
    this.producers,
    this.licensors,
    this.studios,
    this.genres,
    this.explicitGenres,
    this.themes,
    this.demographics,
  });

  factory Anime.fromJson(Map<String, dynamic> json) => _$AnimeFromJson(json);

  Map<String, dynamic> toJson() => _$AnimeToJson(this);
}

// --- Reusable Sub-Classes ---

@JsonSerializable(fieldRename: FieldRename.snake)
class MalEntry {
  final int? malId;
  final String? type;
  final String? name;
  final String? url;

  MalEntry({this.malId, this.type, this.name, this.url});

  factory MalEntry.fromJson(Map<String, dynamic> json) =>
      _$MalEntryFromJson(json);

  Map<String, dynamic> toJson() => _$MalEntryToJson(this);
}

@JsonSerializable()
class Images {
  final ImageSet jpg;
  final ImageSet webp;

  Images({required this.jpg, required this.webp});

  factory Images.fromJson(Map<String, dynamic> json) => _$ImagesFromJson(json);

  Map<String, dynamic> toJson() => _$ImagesToJson(this);
}

@JsonSerializable(fieldRename: FieldRename.snake)
class ImageSet {
  final String? imageUrl;
  final String? smallImageUrl;
  final String? largeImageUrl;

  ImageSet({this.imageUrl, this.smallImageUrl, this.largeImageUrl});

  factory ImageSet.fromJson(Map<String, dynamic> json) =>
      _$ImageSetFromJson(json);

  Map<String, dynamic> toJson() => _$ImageSetToJson(this);
}

@JsonSerializable(fieldRename: FieldRename.snake)
class Trailer {
  final String? youtubeId;
  final String? url;
  final String? embedUrl;

  Trailer({this.youtubeId, this.url, this.embedUrl});

  factory Trailer.fromJson(Map<String, dynamic> json) =>
      _$TrailerFromJson(json);

  Map<String, dynamic> toJson() => _$TrailerToJson(this);
}

@JsonSerializable()
class TitleEntry {
  final String type;
  final String title;

  TitleEntry({required this.type, required this.title});

  factory TitleEntry.fromJson(Map<String, dynamic> json) =>
      _$TitleEntryFromJson(json);

  Map<String, dynamic> toJson() => _$TitleEntryToJson(this);
}

@JsonSerializable()
class Aired {
  final String? from;
  final String? to;
  final AiredProp? prop;
  final String? string;

  Aired({this.from, this.to, this.prop, this.string});

  factory Aired.fromJson(Map<String, dynamic> json) => _$AiredFromJson(json);

  Map<String, dynamic> toJson() => _$AiredToJson(this);
}

@JsonSerializable()
class AiredProp {
  final AiredDate? from;
  final AiredDate? to;

  AiredProp({this.from, this.to});

  factory AiredProp.fromJson(Map<String, dynamic> json) =>
      _$AiredPropFromJson(json);

  Map<String, dynamic> toJson() => _$AiredPropToJson(this);
}

@JsonSerializable()
class AiredDate {
  final int? day;
  final int? month;
  final int? year;

  AiredDate({this.day, this.month, this.year});

  factory AiredDate.fromJson(Map<String, dynamic> json) =>
      _$AiredDateFromJson(json);

  Map<String, dynamic> toJson() => _$AiredDateToJson(this);
}

@JsonSerializable()
class Broadcast {
  final String? day;
  final String? time;
  final String? timezone;
  final String? string;

  Broadcast({this.day, this.time, this.timezone, this.string});

  factory Broadcast.fromJson(Map<String, dynamic> json) =>
      _$BroadcastFromJson(json);

  Map<String, dynamic> toJson() => _$BroadcastToJson(this);
}
